
/*public class Laura
{
    public Meta meta { get; set; }
    public Datum[] data { get; set; }
    public Tags tags { get; set; }
}

public class Meta
{
    public string count { get; set; }
}

public class Tags
{
    public string linkedeventshelfi12 { get; set; }
    public string linkedeventshelfi9 { get; set; }
    public string linkedeventshelmet1 { get; set; }
    public string linkedeventshelmet10592 { get; set; }
    public string linkedeventshelmet10593 { get; set; }
    public string linkedeventshelmet10594 { get; set; }
    public string linkedeventshelmet10595 { get; set; }
    public string linkedeventshelmet10652 { get; set; }
    public string linkedeventshelmet10654 { get; set; }
    public string linkedeventshelmet10655 { get; set; }
    public string linkedeventshelmet10659 { get; set; }
    public string linkedeventshelmet10670 { get; set; }
    public string linkedeventshelmet10672 { get; set; }
    public string linkedeventshelmet10673 { get; set; }
    public string linkedeventshelmet10674 { get; set; }
    public string linkedeventshelmet10675 { get; set; }
    public string linkedeventshelmet10676 { get; set; }
    public string linkedeventshelmet10677 { get; set; }
    public string linkedeventshelmet10689 { get; set; }
    public string linkedeventshelmet10690 { get; set; }
    public string linkedeventshelmet10691 { get; set; }
    public string linkedeventshelmet10737 { get; set; }
    public string linkedeventshelmet10778 { get; set; }
    public string linkedeventshelmet10786 { get; set; }
    public string linkedeventshelmet10791 { get; set; }
    public string linkedeventshelmet10795 { get; set; }
    public string linkedeventshelmet10801 { get; set; }
    public string linkedeventshelmet10817 { get; set; }
    public string linkedeventshelmet10821 { get; set; }
    public string linkedeventshelmet10822 { get; set; }
    public string linkedeventshelmet10823 { get; set; }
    public string linkedeventshelmet10830 { get; set; }
    public string linkedeventshelmet10831 { get; set; }
    public string linkedeventshelmet10833 { get; set; }
    public string linkedeventshelmet10835 { get; set; }
    public string linkedeventshelmet10838 { get; set; }
    public string linkedeventshelmet10840 { get; set; }
    public string linkedeventshelmet10846 { get; set; }
    public string linkedeventshelmet10848 { get; set; }
    public string linkedeventshelmet10851 { get; set; }
    public string linkedeventshelmet10852 { get; set; }
    public string linkedeventshelmet10855 { get; set; }
    public string linkedeventshelmet10856 { get; set; }
    public string linkedeventshelmet11193 { get; set; }
    public string linkedeventshelmet11194 { get; set; }
    public string linkedeventshelmet11274 { get; set; }
    public string linkedeventshelmet11347 { get; set; }
    public string linkedeventshelmet11351 { get; set; }
    public string linkedeventshelmet11405 { get; set; }
    public string linkedeventshelmet11683 { get; set; }
    public string linkedeventshelmet11686 { get; set; }
    public string linkedeventshelmet11687 { get; set; }
    public string linkedeventshelmet11689 { get; set; }
    public string linkedeventshelmet11699 { get; set; }
    public string linkedeventshelmet11727 { get; set; }
    public string linkedeventshelmet11733 { get; set; }
    public string linkedeventshelmet11756 { get; set; }
    public string linkedeventshelmet11767 { get; set; }
    public string linkedeventshelmet11777 { get; set; }
    public string linkedeventshelmet11835 { get; set; }
    public string linkedeventshelmet11893 { get; set; }
    public string linkedeventshelmet11916 { get; set; }
    public string linkedeventshelmet11932 { get; set; }
    public string linkedeventshelmet11996 { get; set; }
    public string linkedeventshelmet11997 { get; set; }
    public string linkedeventshelmet12005 { get; set; }
    public string linkedeventshelmet12006 { get; set; }
    public string linkedeventshelmet12023 { get; set; }
    public string linkedeventshelmet23 { get; set; }
    public string linkedeventshelsinkiaf5ray5xpy { get; set; }
    public string linkedeventshelsinkiaf5ray5xqz { get; set; }
    public string linkedeventshelsinkiaf5razbafu { get; set; }
    public string linkedeventshelsinkiaf5razdfsa { get; set; }
    public string linkedeventshelsinkiaf5razfcfy { get; set; }
    public string linkedeventshelsinkiaf6ray5xqz { get; set; }
    public string linkedeventshelsinkiagavzfzjgy { get; set; }
    public string linkedeventskulke104 { get; set; }
    public string linkedeventskulke105 { get; set; }
    public string linkedeventskulke205 { get; set; }
    public string linkedeventskulke218 { get; set; }
    public string linkedeventskulke29 { get; set; }
    public string linkedeventskulke30 { get; set; }
    public string linkedeventskulke31 { get; set; }
    public string linkedeventskulke32 { get; set; }
    public string linkedeventskulke33 { get; set; }
    public string linkedeventskulke348 { get; set; }
    public string linkedeventskulke351 { get; set; }
    public string linkedeventskulke41 { get; set; }
    public string linkedeventskulke42 { get; set; }
    public string linkedeventskulke44 { get; set; }
    public string linkedeventskulke45 { get; set; }
    public string linkedeventskulke46 { get; set; }
    public string linkedeventskulke47 { get; set; }
    public string linkedeventskulke48 { get; set; }
    public string linkedeventskulke49 { get; set; }
    public string linkedeventskulke50 { get; set; }
    public string linkedeventskulke51 { get; set; }
    public string linkedeventskulke52 { get; set; }
    public string linkedeventskulke53 { get; set; }
    public string linkedeventskulke54 { get; set; }
    public string linkedeventskulke55 { get; set; }
    public string linkedeventskulke596 { get; set; }
    public string linkedeventskulke613 { get; set; }
    public string linkedeventskulke616 { get; set; }
    public string linkedeventskulke669 { get; set; }
    public string linkedeventskulke671 { get; set; }
    public string linkedeventskulke673 { get; set; }
    public string linkedeventskulke732 { get; set; }
    public string linkedeventskulke733 { get; set; }
    public string linkedeventskulke734 { get; set; }
    public string linkedeventskultus1 { get; set; }
    public string linkedeventskultus2 { get; set; }
    public string linkedeventskultus8 { get; set; }
    public string linkedeventsmatkomoottoriurheilu { get; set; }
    public string linkedeventsmatkotapahtuma { get; set; }
    public string linkedeventsysop10 { get; set; }
    public string linkedeventsysop10041 { get; set; }
    public string linkedeventsysop10066 { get; set; }
    public string linkedeventsysop10105 { get; set; }
    public string linkedeventsysop10216 { get; set; }
    public string linkedeventsysop10218 { get; set; }
    public string linkedeventsysop10250 { get; set; }
    public string linkedeventsysop10647 { get; set; }
    public string linkedeventsysop10649 { get; set; }
    public string linkedeventsysop10687 { get; set; }
    public string linkedeventsysop10727 { get; set; }
    public string linkedeventsysop10784 { get; set; }
    public string linkedeventsysop10871 { get; set; }
    public string linkedeventsysop10886 { get; set; }
    public string linkedeventsysop10995 { get; set; }
    public string linkedeventsysop11 { get; set; }
    public string linkedeventsysop1103 { get; set; }
    public string linkedeventsysop11049 { get; set; }
    public string linkedeventsysop11185 { get; set; }
    public string linkedeventsysop11292 { get; set; }
    public string linkedeventsysop11345 { get; set; }
    public string linkedeventsysop11406 { get; set; }
    public string linkedeventsysop1142 { get; set; }
    public string linkedeventsysop11469 { get; set; }
    public string linkedeventsysop1148 { get; set; }
    public string linkedeventsysop11514 { get; set; }
    public string linkedeventsysop11574 { get; set; }
    public string linkedeventsysop11617 { get; set; }
    public string linkedeventsysop11693 { get; set; }
    public string linkedeventsysop11756 { get; set; }
    public string linkedeventsysop11758 { get; set; }
    public string linkedeventsysop11763 { get; set; }
    public string linkedeventsysop1178 { get; set; }
    public string linkedeventsysop11951 { get; set; }
    public string linkedeventsysop11955 { get; set; }
    public string linkedeventsysop12078 { get; set; }
    public string linkedeventsysop12257 { get; set; }
    public string linkedeventsysop12259 { get; set; }
    public string linkedeventsysop1235 { get; set; }
    public string linkedeventsysop12376 { get; set; }
    public string linkedeventsysop12469 { get; set; }
    public string linkedeventsysop12624 { get; set; }
    public string linkedeventsysop12690 { get; set; }
    public string linkedeventsysop12697 { get; set; }
    public string linkedeventsysop1278 { get; set; }
    public string linkedeventsysop1281 { get; set; }
    public string linkedeventsysop12877 { get; set; }
    public string linkedeventsysop12878 { get; set; }
    public string linkedeventsysop1288 { get; set; }
    public string linkedeventsysop1290 { get; set; }
    public string linkedeventsysop1304 { get; set; }
    public string linkedeventsysop13050 { get; set; }
    public string linkedeventsysop13084 { get; set; }
    public string linkedeventsysop13105 { get; set; }
    public string linkedeventsysop13313 { get; set; }
    public string linkedeventsysop13475 { get; set; }
    public string linkedeventsysop13810 { get; set; }
    public string linkedeventsysop13862 { get; set; }
    public string linkedeventsysop13876 { get; set; }
    public string linkedeventsysop13928 { get; set; }
    public string linkedeventsysop13929 { get; set; }
    public string linkedeventsysop13956 { get; set; }
    public string linkedeventsysop14004 { get; set; }
    public string linkedeventsysop14113 { get; set; }
    public string linkedeventsysop1420 { get; set; }
    public string linkedeventsysop14232 { get; set; }
    public string linkedeventsysop143 { get; set; }
    public string linkedeventsysop14336 { get; set; }
    public string linkedeventsysop14380 { get; set; }
    public string linkedeventsysop14559 { get; set; }
    public string linkedeventsysop14614 { get; set; }
    public string linkedeventsysop14710 { get; set; }
    public string linkedeventsysop14722 { get; set; }
    public string linkedeventsysop1485 { get; set; }
    public string linkedeventsysop14853 { get; set; }
    public string linkedeventsysop14993 { get; set; }
    public string linkedeventsysop15095 { get; set; }
    public string linkedeventsysop15198 { get; set; }
    public string linkedeventsysop15292 { get; set; }
    public string linkedeventsysop15403 { get; set; }
    public string linkedeventsysop15427 { get; set; }
    public string linkedeventsysop15521 { get; set; }
    public string linkedeventsysop15536 { get; set; }
    public string linkedeventsysop15697 { get; set; }
    public string linkedeventsysop1571 { get; set; }
    public string linkedeventsysop1574 { get; set; }
    public string linkedeventsysop15757 { get; set; }
    public string linkedeventsysop15769 { get; set; }
    public string linkedeventsysop15817 { get; set; }
    public string linkedeventsysop15818 { get; set; }
    public string linkedeventsysop15822 { get; set; }
    public string linkedeventsysop15875 { get; set; }
    public string linkedeventsysop15937 { get; set; }
    public string linkedeventsysop16019 { get; set; }
    public string linkedeventsysop16116 { get; set; }
    public string linkedeventsysop16210 { get; set; }
    public string linkedeventsysop16230 { get; set; }
    public string linkedeventsysop16241 { get; set; }
    public string linkedeventsysop16327 { get; set; }
    public string linkedeventsysop16351 { get; set; }
    public string linkedeventsysop16485 { get; set; }
    public string linkedeventsysop16486 { get; set; }
    public string linkedeventsysop16554 { get; set; }
    public string linkedeventsysop16575 { get; set; }
    public string linkedeventsysop16603 { get; set; }
    public string linkedeventsysop16866 { get; set; }
    public string linkedeventsysop16891 { get; set; }
    public string linkedeventsysop17015 { get; set; }
    public string linkedeventsysop17018 { get; set; }
    public string linkedeventsysop17083 { get; set; }
    public string linkedeventsysop1715 { get; set; }
    public string linkedeventsysop17179 { get; set; }
    public string linkedeventsysop17392 { get; set; }
    public string linkedeventsysop17522 { get; set; }
    public string linkedeventsysop17567 { get; set; }
    public string linkedeventsysop17581 { get; set; }
    public string linkedeventsysop17654 { get; set; }
    public string linkedeventsysop17728 { get; set; }
    public string linkedeventsysop17741 { get; set; }
    public string linkedeventsysop17790 { get; set; }
    public string linkedeventsysop178 { get; set; }
    public string linkedeventsysop1780 { get; set; }
    public string linkedeventsysop17808 { get; set; }
    public string linkedeventsysop1808 { get; set; }
    public string linkedeventsysop18105 { get; set; }
    public string linkedeventsysop18123 { get; set; }
    public string linkedeventsysop1828 { get; set; }
    public string linkedeventsysop18357 { get; set; }
    public string linkedeventsysop18405 { get; set; }
    public string linkedeventsysop18434 { get; set; }
    public string linkedeventsysop18452 { get; set; }
    public string linkedeventsysop1857 { get; set; }
    public string linkedeventsysop18717 { get; set; }
    public string linkedeventsysop18718 { get; set; }
    public string linkedeventsysop18782 { get; set; }
    public string linkedeventsysop1881 { get; set; }
    public string linkedeventsysop1882 { get; set; }
    public string linkedeventsysop18844 { get; set; }
    public string linkedeventsysop19001 { get; set; }
    public string linkedeventsysop1917 { get; set; }
    public string linkedeventsysop19242 { get; set; }
    public string linkedeventsysop19245 { get; set; }
    public string linkedeventsysop1928 { get; set; }
    public string linkedeventsysop1934 { get; set; }
    public string linkedeventsysop19355 { get; set; }
    public string linkedeventsysop1947 { get; set; }
    public string linkedeventsysop1949 { get; set; }
    public string linkedeventsysop19590 { get; set; }
    public string linkedeventsysop1961 { get; set; }
    public string linkedeventsysop1963 { get; set; }
    public string linkedeventsysop1983 { get; set; }
    public string linkedeventsysop19863 { get; set; }
    public string linkedeventsysop1994 { get; set; }
    public string linkedeventsysop19993 { get; set; }
    public string linkedeventsysop2003 { get; set; }
    public string linkedeventsysop20211 { get; set; }
    public string linkedeventsysop2023 { get; set; }
    public string linkedeventsysop2027 { get; set; }
    public string linkedeventsysop20390 { get; set; }
    public string linkedeventsysop20421 { get; set; }
    public string linkedeventsysop20513 { get; set; }
    public string linkedeventsysop20742 { get; set; }
    public string linkedeventsysop20836 { get; set; }
    public string linkedeventsysop20879 { get; set; }
    public string linkedeventsysop20895 { get; set; }
    public string linkedeventsysop210 { get; set; }
    public string linkedeventsysop2108 { get; set; }
    public string linkedeventsysop21131 { get; set; }
    public string linkedeventsysop21244 { get; set; }
    public string linkedeventsysop21435 { get; set; }
    public string linkedeventsysop2149 { get; set; }
    public string linkedeventsysop21503 { get; set; }
    public string linkedeventsysop2169 { get; set; }
    public string linkedeventsysop21733 { get; set; }
    public string linkedeventsysop21800 { get; set; }
    public string linkedeventsysop22037 { get; set; }
    public string linkedeventsysop22039 { get; set; }
    public string linkedeventsysop2208 { get; set; }
    public string linkedeventsysop2211 { get; set; }
    public string linkedeventsysop22164 { get; set; }
    public string linkedeventsysop22193 { get; set; }
    public string linkedeventsysop2224 { get; set; }
    public string linkedeventsysop22465 { get; set; }
    public string linkedeventsysop22824 { get; set; }
    public string linkedeventsysop23 { get; set; }
    public string linkedeventsysop2315 { get; set; }
    public string linkedeventsysop23218 { get; set; }
    public string linkedeventsysop23373 { get; set; }
    public string linkedeventsysop2339 { get; set; }
    public string linkedeventsysop23411 { get; set; }
    public string linkedeventsysop2351 { get; set; }
    public string linkedeventsysop23551 { get; set; }
    public string linkedeventsysop2371 { get; set; }
    public string linkedeventsysop24219 { get; set; }
    public string linkedeventsysop24328 { get; set; }
    public string linkedeventsysop2433 { get; set; }
    public string linkedeventsysop24352 { get; set; }
    public string linkedeventsysop2445 { get; set; }
    public string linkedeventsysop24516 { get; set; }
    public string linkedeventsysop24644 { get; set; }
    public string linkedeventsysop24856 { get; set; }
    public string linkedeventsysop24860 { get; set; }
    public string linkedeventsysop2492 { get; set; }
    public string linkedeventsysop25147 { get; set; }
    public string linkedeventsysop25261 { get; set; }
    public string linkedeventsysop25338 { get; set; }
    public string linkedeventsysop2573 { get; set; }
    public string linkedeventsysop2625 { get; set; }
    public string linkedeventsysop26281 { get; set; }
    public string linkedeventsysop2643 { get; set; }
    public string linkedeventsysop26481 { get; set; }
    public string linkedeventsysop26626 { get; set; }
    public string linkedeventsysop26907 { get; set; }
    public string linkedeventsysop2699 { get; set; }
    public string linkedeventsysop2712 { get; set; }
    public string linkedeventsysop27158 { get; set; }
    public string linkedeventsysop2717 { get; set; }
    public string linkedeventsysop2739 { get; set; }
    public string linkedeventsysop27390 { get; set; }
    public string linkedeventsysop27499 { get; set; }
    public string linkedeventsysop27506 { get; set; }
    public string linkedeventsysop2762 { get; set; }
    public string linkedeventsysop2771 { get; set; }
    public string linkedeventsysop2787 { get; set; }
    public string linkedeventsysop27962 { get; set; }
    public string linkedeventsysop28114 { get; set; }
    public string linkedeventsysop28276 { get; set; }
    public string linkedeventsysop2834 { get; set; }
    public string linkedeventsysop2841 { get; set; }
    public string linkedeventsysop28435 { get; set; }
    public string linkedeventsysop2846 { get; set; }
    public string linkedeventsysop2850 { get; set; }
    public string linkedeventsysop2851 { get; set; }
    public string linkedeventsysop28612 { get; set; }
    public string linkedeventsysop2901 { get; set; }
    public string linkedeventsysop29150 { get; set; }
    public string linkedeventsysop29165 { get; set; }
    public string linkedeventsysop29336 { get; set; }
    public string linkedeventsysop29381 { get; set; }
    public string linkedeventsysop29762 { get; set; }
    public string linkedeventsysop29804 { get; set; }
    public string linkedeventsysop29838 { get; set; }
    public string linkedeventsysop29905 { get; set; }
    public string linkedeventsysop29932 { get; set; }
    public string linkedeventsysop300 { get; set; }
    public string linkedeventsysop30021 { get; set; }
    public string linkedeventsysop30071 { get; set; }
    public string linkedeventsysop30096 { get; set; }
    public string linkedeventsysop30129 { get; set; }
    public string linkedeventsysop30169 { get; set; }
    public string linkedeventsysop30173 { get; set; }
    public string linkedeventsysop3050 { get; set; }
    public string linkedeventsysop3064 { get; set; }
    public string linkedeventsysop3065 { get; set; }
    public string linkedeventsysop3111 { get; set; }
    public string linkedeventsysop3137 { get; set; }
    public string linkedeventsysop316 { get; set; }
    public string linkedeventsysop33353 { get; set; }
    public string linkedeventsysop339 { get; set; }
    public string linkedeventsysop3521 { get; set; }
    public string linkedeventsysop3522 { get; set; }
    public string linkedeventsysop3542 { get; set; }
    public string linkedeventsysop360 { get; set; }
    public string linkedeventsysop3670 { get; set; }
    public string linkedeventsysop3684 { get; set; }
    public string linkedeventsysop372 { get; set; }
    public string linkedeventsysop37874 { get; set; }
    public string linkedeventsysop38025 { get; set; }
    public string linkedeventsysop38028 { get; set; }
    public string linkedeventsysop38044 { get; set; }
    public string linkedeventsysop38310 { get; set; }
    public string linkedeventsysop38773 { get; set; }
    public string linkedeventsysop3910 { get; set; }
    public string linkedeventsysop3917 { get; set; }
    public string linkedeventsysop39492 { get; set; }
    public string linkedeventsysop39586 { get; set; }
    public string linkedeventsysop39598 { get; set; }
    public string linkedeventsysop3984 { get; set; }
    public string linkedeventsysop4059 { get; set; }
    public string linkedeventsysop407 { get; set; }
    public string linkedeventsysop4074 { get; set; }
    public string linkedeventsysop4098 { get; set; }
    public string linkedeventsysop419 { get; set; }
    public string linkedeventsysop4295 { get; set; }
    public string linkedeventsysop4330 { get; set; }
    public string linkedeventsysop4354 { get; set; }
    public string linkedeventsysop4363 { get; set; }
    public string linkedeventsysop4402 { get; set; }
    public string linkedeventsysop4440 { get; set; }
    public string linkedeventsysop4445 { get; set; }
    public string linkedeventsysop4482 { get; set; }
    public string linkedeventsysop4483 { get; set; }
    public string linkedeventsysop4484 { get; set; }
    public string linkedeventsysop4615 { get; set; }
    public string linkedeventsysop4621 { get; set; }
    public string linkedeventsysop4622 { get; set; }
    public string linkedeventsysop4666 { get; set; }
    public string linkedeventsysop4679 { get; set; }
    public string linkedeventsysop4750 { get; set; }
    public string linkedeventsysop478 { get; set; }
    public string linkedeventsysop485 { get; set; }
    public string linkedeventsysop4892 { get; set; }
    public string linkedeventsysop4907 { get; set; }
    public string linkedeventsysop4923 { get; set; }
    public string linkedeventsysop4934 { get; set; }
    public string linkedeventsysop5000 { get; set; }
    public string linkedeventsysop5007 { get; set; }
    public string linkedeventsysop5121 { get; set; }
    public string linkedeventsysop5127 { get; set; }
    public string linkedeventsysop5139 { get; set; }
    public string linkedeventsysop5186 { get; set; }
    public string linkedeventsysop5201 { get; set; }
    public string linkedeventsysop5225 { get; set; }
    public string linkedeventsysop5231 { get; set; }
    public string linkedeventsysop5234 { get; set; }
    public string linkedeventsysop5321 { get; set; }
    public string linkedeventsysop5351 { get; set; }
    public string linkedeventsysop5378 { get; set; }
    public string linkedeventsysop5450 { get; set; }
    public string linkedeventsysop5454 { get; set; }
    public string linkedeventsysop5470 { get; set; }
    public string linkedeventsysop5504 { get; set; }
    public string linkedeventsysop556 { get; set; }
    public string linkedeventsysop5590 { get; set; }
    public string linkedeventsysop5640 { get; set; }
    public string linkedeventsysop6 { get; set; }
    public string linkedeventsysop6033 { get; set; }
    public string linkedeventsysop6062 { get; set; }
    public string linkedeventsysop6165 { get; set; }
    public string linkedeventsysop6198 { get; set; }
    public string linkedeventsysop6213 { get; set; }
    public string linkedeventsysop6231 { get; set; }
    public string linkedeventsysop626 { get; set; }
    public string linkedeventsysop6357 { get; set; }
    public string linkedeventsysop6408 { get; set; }
    public string linkedeventsysop6409 { get; set; }
    public string linkedeventsysop6421 { get; set; }
    public string linkedeventsysop6455 { get; set; }
    public string linkedeventsysop6735 { get; set; }
    public string linkedeventsysop6889 { get; set; }
    public string linkedeventsysop6963 { get; set; }
    public string linkedeventsysop6998 { get; set; }
    public string linkedeventsysop7016 { get; set; }
    public string linkedeventsysop7037 { get; set; }
    public string linkedeventsysop7057 { get; set; }
    public string linkedeventsysop709 { get; set; }
    public string linkedeventsysop7157 { get; set; }
    public string linkedeventsysop7266 { get; set; }
    public string linkedeventsysop742 { get; set; }
    public string linkedeventsysop7596 { get; set; }
    public string linkedeventsysop7642 { get; set; }
    public string linkedeventsysop7643 { get; set; }
    public string linkedeventsysop768 { get; set; }
    public string linkedeventsysop7708 { get; set; }
    public string linkedeventsysop7813 { get; set; }
    public string linkedeventsysop7818 { get; set; }
    public string linkedeventsysop7858 { get; set; }
    public string linkedeventsysop790 { get; set; }
    public string linkedeventsysop7966 { get; set; }
    public string linkedeventsysop7969 { get; set; }
    public string linkedeventsysop7995 { get; set; }
    public string linkedeventsysop8025 { get; set; }
    public string linkedeventsysop8105 { get; set; }
    public string linkedeventsysop8107 { get; set; }
    public string linkedeventsysop8113 { get; set; }
    public string linkedeventsysop8144 { get; set; }
    public string linkedeventsysop8195 { get; set; }
    public string linkedeventsysop8291 { get; set; }
    public string linkedeventsysop84 { get; set; }
    public string linkedeventsysop855 { get; set; }
    public string linkedeventsysop8630 { get; set; }
    public string linkedeventsysop8631 { get; set; }
    public string linkedeventsysop8718 { get; set; }
    public string linkedeventsysop8780 { get; set; }
    public string linkedeventsysop8781 { get; set; }
    public string linkedeventsysop8955 { get; set; }
    public string linkedeventsysop9028 { get; set; }
    public string linkedeventsysop9087 { get; set; }
    public string linkedeventsysop9088 { get; set; }
    public string linkedeventsysop916 { get; set; }
    public string linkedeventsysop9244 { get; set; }
    public string linkedeventsysop9270 { get; set; }
    public string linkedeventsysop934 { get; set; }
    public string linkedeventsysop935 { get; set; }
    public string linkedeventsysop9375 { get; set; }
    public string linkedeventsysop9376 { get; set; }
    public string linkedeventsysop9380 { get; set; }
    public string linkedeventsysop9509 { get; set; }
    public string linkedeventsysop9592 { get; set; }
    public string linkedeventsysop9593 { get; set; }
    public string linkedeventsysop9607 { get; set; }
    public string linkedeventsysop965 { get; set; }
    public string linkedeventsysop969 { get; set; }
    public string linkedeventsysop9700 { get; set; }
    public string linkedeventsysop9734 { get; set; }
    public string linkedeventsysop9860 { get; set; }
    public string linkedeventsysop9882 { get; set; }
}

public class Datum
{
    public string id { get; set; }
    public Name name { get; set; }
    public Source_Type source_type { get; set; }
    public string info_url { get; set; }
    //public DateTime modified_at { get; set; }
    public Location location { get; set; }
    public Description description { get; set; }
    public Tag[] tags { get; set; }
    public Event_Dates event_dates { get; set; }
}

public class Name
{
    public string fi { get; set; }
    public string en { get; set; }
    public string sv { get; set; }
    public string zh { get; set; }
}

public class Source_Type
{
    public int id { get; set; }
    public string name { get; set; }
}

public class Location
{
    public float lat { get; set; }
    public float lon { get; set; }
    public Address address { get; set; }
}

public class Address
{
    public string street_address { get; set; }
    public string postal_code { get; set; }
    public string locality { get; set; }
    public object neighbourhood { get; set; }
}

public class Description
{
    public string intro { get; set; }
    public string body { get; set; }
    public Image[] images { get; set; }
}

public class Image
{
    public string url { get; set; }
    public string copyright_holder { get; set; }
    public License_Type license_type { get; set; }
    public object media_id { get; set; }
}

public class License_Type
{
    public int id { get; set; }
    public string name { get; set; }
}

public class Event_Dates
{
   // public DateTime? starting_day { get; set; }
   // public DateTime? ending_day { get; set; }
    public object additional_description { get; set; }
}

public class Tag
{
    public string id { get; set; }
    public string name { get; set; }
}

*/